### ISSUE TITLE
Auth0 token generated on node 6.2.2 stable doesn't get validated for GET all users

### ISSUE THREAD

**Issue by crashuniverse** [auth0/auth0-api-tokens#4]
We have an auth0 application that works perfectly on node 4.2.4 and we recently when upgraded to node 6.2.2 breaks because of invalid token. A sample request that fails is:

```
❯❯❯ curl -iH "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE0Njg1MDY2OTIsInNjb3BlcyI6eyJ1c2VycyI6eyJhY3Rpb25zIjpbInJlYWQiXX19LCJqdGkiOiJmOTBiZWYxNzUwMWVkODYzY2Y5ZDgxODZhZThmNThjNyIsImV4cCI6MTQ2ODUxMDI5MiwiYXVkIjoiaEQycExGS1Zib2JmVXNld0tURDFYV2h2TmhGMlhzTjEifQ._Fb7Dyii61QPvSz5bkp2oqGWiq0Qn5R8zjBWhrh1U2A" https://cleansheet.auth0.com/api/v2/users
HTTP/1.1 401 Unauthorized
Date: Thu, 14 Jul 2016 14:50:47 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 192
Connection: keep-alive
WWW-Authenticate: Bearer error="Invalid signature received for JSON Web Token validation"
vary: origin
cache-control: no-cache

{"statusCode":401,"error":"Unauthorized","message":"Invalid signature received for JSON Web Token validation","attributes":{"error":"Invalid signature received for JSON Web Token validation"}}%
```

What I know at the moment is:
- Tokens generated from node 4.2.4 works fine and returns 200 status.
- The above mentioned token in curl request when used on http://jwt.io with api secret says verified, meaning secret works fine too.

**Comment by simonmcmanus** [comment]
I'm seeing the same thing since upgrading to node v6.3.1

**Comment by fabien** [comment]
Same here on node v6.9.1 - just forked to handle it on my own for now.

Does anyone know if the fix targets a known breaking change (from v.4 to v.6)?

**Comment by seamusabshere** [comment]
any chance your auth0 secret needs to be base64 URL decoded before being used as the JWT secret?

this fixed it for me in rubyland:

```
# broken
token = JWT.encode payload, secret, 'HS256'
# fixed
token = JWT.encode payload, JWT.base64url_decode(secret), 'HS256'
```
